### ISSUE TITLE
Tipo in _ParseASEventToVEvent

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#1]
There is tipo in _ParseASEventToVEvent
-                               $att_str = sprinf("CN=%s:MAILTO:%s", $att->name, $att->email);
-                               $att_str = sprintf("CN=%s:MAILTO:%s", $att->name, $att->email);

**Comment by dupondje** [comment]
Comitted!

Op 17-04-12 16:16, xbgmsharp schreef:

**Comment by xbgmsharp** [comment]
it was an easy one.
Closing
