### ISSUE TITLE
Don't query all backends for every user

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#10]
Even when I disable "Mail" for an Exchange/Z-Push inside iOS after adding a new account (just enabling e.g. Calendars and Reminders), BackendIMAP still runs and syncs everything, even though the phone is not going to show any email messages because we disabled that part...
Even though I have 2 backends enabled (imap & caldav), shouldn't we just provide the data that the phone asks for, instead of always running all backends?

This is because in BackendCombined->Logon() we always iterate over all availble (i.e. enabled in combined/config.php) backends, independent of what the user enabled or disabled on her device:

foreach ($this->backends as $i => $b){
[..]
if($this->backends[$i]->Logon($u, $d, $p) == false){

Ideal would be: Depending on the users choice, we only call Logon for those Backends that are active! For instance:
- All users have IMAP accounts
- Some users have CalDAV accounts
- Few users have LDAP accounts

At the moment, this scenario is not possible because if LDAP is enabled and fails (e.g. user does not have an account), not even the IMAP functionality works because the Backend->Logon throws an error.

**Comment by dupondje** [comment]
This is not possible with ActiveSync.
On the first request it needs to Login to all backends, and after that response, the requested folders are send.
