### ISSUE TITLE
Use ldap_v1 for php-push-2?

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#12]
I got the old LDAP backend in php-push-1 to work perfectly, with adding/removing contacts, with good mapping of LDAP and AS attributes, and even private and public contacts via 2 different LDAP DNs.

What is your plan with LDAP, as this is a critical component: are you actively developing this, and therefore there is this loop? Can we reuse the LDAPv1 backend, even though it is limited to two collections?

**Comment by dupondje** [comment]
Its not possible to just use ldap code from PHP-Push(1).
WIP on a LDAP backend for PHP-Push 2

**Comment by fortiko** [comment]
Apart from ChangeMessage (see separate issue), LDAP mostly seems to work now.
