### ISSUE TITLE
Use correct LDAP protocol and user dn in backend/ldap.php

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#14]
Fix backend/ldap.php to use the correct LDAP protocol and user dn (which is usually not $username as in imap or caldav):

Also: enable %u substitution (and others if required):

```
    public function Logon($username, $domain, $password)
    {
    $my_LDAP_USER_DN = str_replace('%u', $username, LDAP_USER_DN);
    $this->ldap_link = ldap_connect(LDAP_SERVER, LDAP_PORT);
    ldap_set_option($this->ldap_link, LDAP_OPT_PROTOCOL_VERSION, 3);
    if (ldap_bind($this->ldap_link, $my_LDAP_USER_DN, $password))
    {
```

Without this, I cannot even connect to slapd on Ubuntu. With this change, I can connect successfully, but now getmessage etc required LDAP_BASE_DNS (see the other issue) which I cannot figure out.

**Comment by fortiko** [comment]
Nope:

```
            if (ldap_bind($this->ldap_link, $username $password))
```

should be 

```
            if (ldap_bind($this->ldap_link, $user_dn, $password))
```

**Comment by dupondje** [comment]
Fixed!
