### ISSUE TITLE
Implement "Real Names", perhaps via IMAP_USERNAME_FULLNAME

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#16]
The AS12.1 branch of php-push has an interesting feature to avoid using "user@domain.tld" as the "From:" as it is now the case:

```
// Define username => fullname changes here
define('IMAP_USERNAME_FULLNAME', serialize(array(
        'user1'=>'Lastname1, Firstname1',
        'user2'=>'Lastname2, Firstname2',
        )));
```

Is something like this planned, perhaps even via z-push-2?

See also these related posts, perhaps the authors of those post would like to contribute:

http://z-push.sourceforge.net/phpbb/viewtopic.php?f=4&t=1642&start=10#p6091
http://z-push.sourceforge.net/phpbb/viewtopic.php?f=4&t=2005#p7121

**Comment by dupondje** [comment]
Not going to change anything on the existing backends from z-push.
If you want something in the IMAP backend, please file a bug there.

Thanks
