### ISSUE TITLE
Fix for cutoff date in ldap.php

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#17]
The cutoff date for the LDAP filter is in the wrong format:

$cutoff = date("Ymd\THis\Z", $cutoffdate);

should be

$cutoff = date("YmdHis.0\Z", $cutoffdate);

See also this: http://www.tech-archive.net/Archive/Windows/microsoft.public.windows.server.active_directory/2008-06/msg00949.html

With the updated cutoff date filter, at least the number of contacts is correctly obtained.

**Comment by dupondje** [comment]
OpenLDAP has the following format:
20110510184009Z

So it was indeed wrong, but .0 shouldn't be added.

**Comment by fortiko** [comment]
I tried the fix as I described it, and it works. Did you try your format?
