### ISSUE TITLE
SYNC_FOLDER_TYPE_XXX VS SYNC_FOLDER_TYPE_USER_XXX

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#2]
In GetFolder I add additional Folder type.
I am not about the difference but according to the name it does make sense.
What do you think?
-                       $folder->type = SYNC_FOLDER_TYPE_APPOINTMENT;
-                        if (substr($id, 1) == "personal")
-                                $folder->type = SYNC_FOLDER_TYPE_APPOINTMENT;
-                        else
-                                $folder->type = SYNC_FOLDER_TYPE_USER_APPOINTMENT;
              }
              else
              {
-                       $folder->type = SYNC_FOLDER_TYPE_TASK;
-                        if (substr($id, 1) == "personal")
-                                $folder->type = SYNC_FOLDER_TYPE_TASK;
-                        else
-                                $folder->type = SYNC_FOLDER_TYPE_USER_TASK;

**Comment by dupondje** [comment]
Comitted a bit different.
In you config you define('CALDAV_PERSONAL', 'personal'); and then it 
will do what you want :)

But this way the personal can be some other folder OR nothing.

Tx

Op 17-04-12 16:18, xbgmsharp schreef:

**Comment by xbgmsharp** [comment]
Sound nice.
Do you know the difference between those 2?
Does it make sense to use them?
