### ISSUE TITLE
Use IMAP backend for Notes/Journal

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#25]
With iOS 4+, you can store notes on a regular IMAP account in a special folder called "Notes".

Could a similar setup be used to offer Notes/Journal functionality with the IMAP backend? At the moment, this only seems to work with Zarafa, but using IMAP should be straight forward.

Thanks!

**Comment by fortiko** [comment]
Some additional information:

Technical details on how notes can be stored on IMAP even from Thunderbird:
http://maft.co.uk/musings/2012/how-to-icloud-notes-in-mozilla-thunderbird/

There is also an app to use the IMAP/Notes container from Android devices:
http://code.google.com/p/imapnote/

**Comment by dupondje** [comment]
IMAP backend requests go to Z-Push please.
Thanks

**Comment by fortiko** [comment]
Now that you are a contributor to z-push (congratulations!?), would you reconsider opening this issue? I also added it to z-push (as far as I can remember), it seems like a low hanging fruit since Mail.app and iOS already support it and would add another nice backend to php-push.

Thanks for considering!

**Comment by dupondje** [comment]
I surely want to look at it, but I think its better to open a bug for it at z-push's bugtracker. Then the bug will be tracker the correct place (which isn't here :))

**Comment by fortiko** [comment]
http://z-push.sourceforge.net/phpbb/viewtopic.php?f=7&t=2057&p=7265#p7265
