### ISSUE TITLE
Setting Free, Busy, Tentative, or Out of Office status not working

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#28]
The mapping for Free, Busy, Tentative, or Out of Office [1] seems to be broken in some places. When creating a new event with a certain availability, that availability is not stored as part of the event. After inviting another person to the event, availability automatically becomes (correctly) updated to the previous selection.

Without invitees no availability information, it appears.

Also, "busy" on iOS shows up as "tentative" in Lightning with DAViCal backend, "tentative" reverts back to free, and "out of office" becomes "busy". There seems to be a mapping mixup somewhere between from and to device/caldav.

[1] http://msdn.microsoft.com/en-us/library/ms526656%28v=exchg.10%29.aspx

**Comment by dupondje** [comment]
Some things just cant be mapped 1:1 to ical
busystatus is mapped to TRANSP
http://www.kanzaki.com/docs/ical/transp.html

Only 2 values, so 1:1 is impossible.
