### ISSUE TITLE
Pasre timezone

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#3]
There is still an timezone parse issue in _MakeUTCDate
-                       $tz = timezone_open($timezone);
-                       $tz = timezone_open($this->_ParseTimezone($timezone));

**Comment by dupondje** [comment]
Committed a bit different.
_MakeUTCDate should only be called with a valid timezone, so the parsing 
is before the _MakeUTCDate.

Anyway this should be fixed.

Op 17-04-12 16:21, xbgmsharp schreef:
