### ISSUE TITLE
Roundcube plugin to offer remote wipe GUI

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#31]
Implement a RC plugin that offers the user to select any of his devices to remove wipe, as shown here for Zarafa:

Functionality:
http://z-push.sourceforge.net/phpbb/viewtopic.php?f=4&t=802

Screenshot:
http://z-push.sourceforge.net/phpbb/download/file.php?id=1&sid=962a7bf85c23a9ee8c30501f711c17d2

```
z-push-admin.php -a list -u user@domain.tld
```

shows a list of all devices for a specific user. Show the resulting output nicely formatted in a list for the user to pick the device:

```
Synchronized devices of user: user@domain.tld
-----------------------------------------------------
DeviceId:               ApplXXXXXXXXXX
Device type:            iPhone
UserAgent:              Apple-iPhone3C1/11.222
ActiveSync version:     2.5
First sync:             2012-01-03 09:36
Last sync:              2012-04-03 17:05
Total folders:          129
Synchronized folders:   4
Synchronized data:      Emails Tasks Calendars Contacts 
Status:                 OK
WipeRequest on:         not set
WipeRequest by:         not set
Wiped on:               not set
Attention needed:       No errors known
```

**Comment by fortiko** [comment]
We can even use the code available from http://www.zarafa.com/integrations/mobile-device-management-plugin

**Comment by dupondje** [comment]
Feel free to code such a roundcube plugin.
But this is quite out of the current scope of PHP-Push, so I won't fix this (soon).
