### ISSUE TITLE
Z-push move trunk

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#36]
Hi,

How did you manage the trunk move from the svn of zpush?
I am unable to do it using git for sogosync.
http://z-push.sourceforge.net/phpbb/viewtopic.php?f=5&t=2040

Regards,
Francois

**Comment by dupondje** [comment]
We are not based on trunk, but on released version (last now Z-Push 2 beta5).
So the location of the trunk doesn't matter :)

**Comment by xbgmsharp** [comment]
You don't sync from the svn?
I am unable to do it using git for sogosync.
http://z-push.sourceforge.net/phpbb/viewtopic.php?f=5&t=2040
