### ISSUE TITLE
Unmet condition in object from type SyncAppointment

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#37]
When doing a sync i do have a lot of this warning then error in the log.

07/06/2012 16:45:19 [20741] [sogo1] [ WARN] [Appl879409CX3NQ] SyncObject->Check(): Unmet condition in object from type 
SyncAppointment: parameter 'starttime' can not be compared, as the comparable is not set. Check failed!
07/06/2012 16:45:19 [20741] [sogo1] [ERROR] [Appl879409CX3NQ] Ignored broken message (SyncAppointment). Reason: '4' Folderid: 'c/Csogo3_personal' message id '6763-4C11ED00-4B-33D231C0.ics'
07/06/2012 16:45:19 [20741] [sogo1] [DEBUG] [Appl879409CX3NQ] ImportChangesStream->ImportMessageChange('6763-4C11ED00-4B-33D231C0.ics'): message ignored and requested to be removed from mobile

The vcard is as following:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Inverse inc./SOGo 1.0//EN
BEGIN:VEVENT
UID:6763-4C11ED00-4B-33D231C0
SUMMARY:Every month
CREATED:20100611T080001Z
DTSTAMP:20100611T080001Z
LAST-MODIFIED:20100611T080956Z
DTSTART;TZID=/inverse.ca/20091015_1/Europe/Madrid:20100618T180000
DTEND;TZID=/inverse.ca/20091015_1/Europe/Madrid:20990617T210000
TRANSP:OPAQUE
SEQUENCE:2
RRULE:INTERVAL=1;FREQ=MONTHLY
END:VEVENT
BEGIN:VTIMEZONE
TZID:/inverse.ca/20091015_1/Europe/Madrid
X-LIC-LOCATION:Europe/Madrid
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

**Comment by dupondje** [comment]
Could you enable DEBUG_WBXML, and tell me what you do exactly, and then 
show me the FULL debug output.
Never had this error, weird :)

**Comment by xbgmsharp** [comment]
I send you the log last week by email.
After farther debugging in found this.

So I do get this when i sync an event from my iphone.
16/06/2012 13:41:02 [ 1636] [test] [ WARN] [Appl879409CX3NQ] SyncAppointment->Check(): Parameter 'organizername' and 'organizeremail' should be set for a meeting request

However this append directly from the iphone (iOS5.1.1).
This message is generate by lib/syncobjects/syncappointment.php
According to:
lib/core/zpushdefs.php:247:define("SYNC_POOMCAL_ORGANIZERNAME","POOMCAL:OrganizerName");

You are looking for the wrong value.

Here is the WBXML debug from the iPhone.

16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I        POOMCAL:MeetingStatus
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I         1
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I        /POOMCAL:MeetingStatus
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I        POOMCAL:Attendees
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I         POOMCAL:Attendee
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I          POOMCAL:Name
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I           My name
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I          /POOMCAL:Name
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I          POOMCAL:Email
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I           name@domain.com
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I          /POOMCAL:Email
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I         /POOMCAL:Attendee
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I        /POOMCAL:Attendees
16/06/2012 13:41:02 [ 1636] [test] [WBXML] [Appl879409CX3NQ] I       </Data>

Thanks and regards

**Comment by dupondje** [comment]
Well in fact its your Phone that needs to send the OrganizerName & OrganizerEmail.
Eventually I could work around this by using the loginname for example as Organizer details ... Gotto check this :)

**Comment by dupondje** [comment]
https://github.com/dupondje/PHP-Push-2/commit/d38090ecf172351c4941dec264975b367caaf876
this is a better fix now :)

**Comment by xbgmsharp** [comment]
Let me check and come back to you
