### ISSUE TITLE
diffbackend/diffstate.php:257 Invalid argument supplied for foreach() (2)

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#39]
Not sure it is link to my preious issue but i do get a php error.
Did you update to the latest z-push-2 version or do you maintain your own branch?

16/06/2012 12:51:30 [ 1637] [user] [ WARN] [Appl879409CX3NQ] SyncAppointment->Check(): Parameter 'organizername' and 'organizeremail' should be set for a meeting request
16/06/2012 12:51:30 [ 1637] [user] [DEBUG] [Appl879409CX3NQ] BackendCalDAV->StatMessage('Cpersonal','97101d90-1bce-4b1d-9902-8c7034701489.ics')
16/06/2012 12:51:31 [ 1637] [user] [ WARN] [Appl879409CX3NQ] /var/www/sogosync/lib/default/diffbackend/diffstate.php:257 Invalid argument supplied for foreach() (2)

**Comment by xbgmsharp** [comment]
i saw you fix it in a previous commit.
However i ask z-push to implement you fix and they answer.
"
I've stated it already a couple of times in the forum and also in Zarafa's public chat - we can't push community contributions without a contributor's agreement. 
"

**Comment by dupondje** [comment]
This has been fixed in the PHP-Push code indeed.
I'm checking if I can sign a contributor agreement, so those things get fixed in z-push also.

Anyway, as the fix is included here, I close the issue.
