### ISSUE TITLE
Missing timezone parsing format

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#4]
While testing i found additional timezone format, which generate warning

timezone_open(): Unknown or bad timezone (Helsinki\, Kiev\, Riika\, Tallinna\, Sofia\, Vilna) (2)
TZID:Helsinki\, Kiev\, Riika\, Tallinna\, Sofia\, Vilna

TZID:/inverse.ca/20101018_1/America/Argentina/Buenos_Aires
timezone_open(): Unknown or bad timezone (America/Argentina) (2)

DTSTART;TZID="Europe/Budapest":20110903T000000
timezone_open(): Unknown or bad timezone ("Europe/Budapest") (2)

TZID:UTC +0100 (Standard) / UTC +0200 (Daylight)

**Comment by dupondje** [comment]
TZID:Helsinki\, Kiev\, Riika\, Tallinna\, Sofia\, Vilna
=> Annoying to parse this, as we don't have all the data we need (the 
continent)
We could loop over all known continents, but that sux a bit ....

TZID:/inverse.ca/20101018_1/America/Argentina/Buenos_Aires
=> Changed existing regex a bit, this should be parsed perfectly

DTSTART;TZID="Europe/Budapest":20110903T000000
=> trimming the " " added, should be fine now.

TZID:UTC +0100 (Standard) / UTC +0200 (Daylight)
=> This sux, and can't be parsed correctly imo.
You could loop over all timezones, and see which one matches... but sux :)

Op 17-04-12 16:55, xbgmsharp schreef:
