### ISSUE TITLE
Caldav Reminder lost from mobile to caldav.

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#40]
Syncing from mobile to caldav disables reminders, for changed events as well as for events newly created on the mobile.

After a sync the entry is like this:
BEGIN:VALARM
TRIGGER:-PT0H60M0S
END:VALARM

However it does not seen to undestand by caldav server.

the entry was:
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT5M
DESCRIPTION:Description
END:VALARM

This should do the trick

--- a/backend/caldav.php
+++ b/backend/caldav.php
@@ -815,7 +815,7 @@ class BackendCalDAV extends BackendDiff {
                {
                        $valarm = new iCalComponent();
                        $valarm->SetType("VALARM");
-                       $trigger = "-PT0H" . $data->reminder . "M0S";
-                       $trigger = "VALUE=DURATION:-PT" . $data->reminder . "M";
                      $valarm->AddProperty("TRIGGER", $trigger);
                      $vevent->AddComponent($valarm);
              }

**Comment by dupondje** [comment]
This should be fixed now.
But notice that VALUE=DURATION is OPTIONAL (http://www.kanzaki.com/docs/ical/trigger.html).
So it shouldn't be needed. Can you test if it works fine now?

**Comment by xbgmsharp** [comment]
the following work in thundebrid
-                       $valarm->AddProperty("ACTION" , "DISPLAY");
-                       $trigger = "-PT" . $data->reminder . "M";
-                       $valarm->AddProperty("TRIGGER;VALUE=DURATION", $trigger);

**Comment by dupondje** [comment]
Action got added now. Could you see if its working fine?

**Comment by xbgmsharp** [comment]
If you add the last fixe i added it works fine.
Your commit is not enough, 1099206

**Comment by dupondje** [comment]
But with https://github.com/dupondje/PHP-Push-2/commit/bb93cb8d0579c3c76a6d9cf8fe1c594dd68050ed it works?

**Comment by xbgmsharp** [comment]
Nope
I did have to havethe DURATION
Even so it is officially not mandatory Thunderbird and IOS require it.

$valarm->AddProperty("TRIGGER;VALUE=DURATION", $trigger);

**Comment by dupondje** [comment]
Hi

What version of Thunderbird?
I do not have VALUE=DURATION, and it works just fine in TB.

**Comment by xbgmsharp** [comment]
I use TB10.0.5
I will recheck
