### ISSUE TITLE
403 in ChangeMessage

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#41]
When i update an calendar entry.
the PUT method return a 403 which i don't undestand as i can fetch the calendar and all other method works fine.

$etag_new = $this->_caldav->DoPUTRequest($url, $data, $etag);

However as there is no return code check, the mobile think it is ok but it is not.
From caldav-client-v2.php the  value $etag_new  return is empty and should be check.

**Comment by xbgmsharp** [comment]
So it seen to be due to the same etag being send.
I got this in my caldav server

Jun 16 20:35:27 sogod [26690]: <<0x09016000[SOGoAppointmentObject]:97101d90-1bce-4b1d-9902-8c7034701489.ics>>D etag '"gcs00000004"' matches: "gcs00000004"

However it does work if i do the change in Thunderbird and i have the same log entry.

Jun 16 20:54:04 sogod [26690]: <<0x08EEBCA8[SOGoAppointmentObject]:97101d90-1bce-4b1d-9902-8c7034701489.ics>>D etag '"gcs00000004"' matches: "gcs00000004"
[16/Jun/2012:20:54:04 GMT] "PUT /SOGo/dav/myuser/Calendar/personal/97101d90-1bce-4b1d-9902-8c7034701489.ics HTTP/1.1" 204 0/764 0.237 - - 0

**Comment by dupondje** [comment]
Could you eventually give more debug output in the caldav server?
Why exactly it returns a 403...

The etag should be given, else you create a new entry, and now a change.

**Comment by xbgmsharp** [comment]
the PUT method is return 403
[16/Jun/2012:20:51:12 GMT] "PUT /SOGo/dav/myuser/Calendar/personal/97101d90-1bce-4b1d-9902-8c7034701489.ics HTTP/1.1" 403 189/498 0.009 - - 0
When calling, $this->_caldav->DoPUTRequest in caldav-client.

Using RESTClient plugin in Firefox, i am able to reproduce the error.
Using dump_io module in Apache i got the full HTTP request.

Apparently the issue is the missing entry: ORGANIZER

**Comment by xbgmsharp** [comment]
This is link to issue #37
As it is missing the ORGANIZER entry the new value is refuse.
So i believe ORGANIZER is badly parse.
