### ISSUE TITLE
Exceptions of recurring events not working

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#44]
Hello,

the ics from the mobile looks like this:
BEGIN:VEVENT
UID:w47NyBF44F3TX73HBAFbn3
SUMMARY:Test handy
DESCRIPTION;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:t=C3=A4glich=20mit=20einer=20ausnahme
DTSTART:20120627T080000Z
DTEND:20120627T090000Z
X-EPOCAGENDAENTRYTYPE:APPOINTMENT
CLASS:PUBLIC
SEQUENCE:0
X-METHOD:NONE
RRULE:D1 20120702T100000
EXDATE:20120628T080000Z
AALARM;TYPE=X-EPOCSOUND:20120627T074500Z;;;
LAST-MODIFIED:20120626T183350Z
PRIORITY:5
X-SYMBIAN-LUID:16740
END:VEVENT

When transferring it to SOGo, the exception (from EXDATE) is lost.

In z-push.log, I can see the following line:
26/06/2012 20:35:11 [27415][user][DEBUG] BackendCalDAV->ChangeMessage('VCalendar[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//php-push//NONSGML PHP-Push Calendar//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20120626T183509Z
LAST-MODIFIED:20120626T183509Z
DTSTART:20120627T080000Z
SUMMARY:Test handy
DTEND:20120627T090000Z
RRULE:FREQ=DAILY;COUNT=6;INTERVAL=1
CLASS:PUBLIC
TRANSP:OPAQUE
DESCRIPTION:täglich mit einer ausnahme
UID:20120626T183511Z-0dffa643c69fa56b3870820aa87e9b8f
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR
]

This seems to be missing the EXDATE entry.

**Comment by dupondje** [comment]
Please try the change I just commited.

**Comment by xbgmsharp** [comment]
Thanks for the quick fix
