### ISSUE TITLE
Is there an installation doc?

### ISSUE THREAD

**Issue by jhaar** [dupondje/PHP-Push-2#45]
Sorry for the naive question, but I can figure out how to get BackendIMAP to work - but how to I get IMAP&CalDAV&LDAP working in the same z-push? I assume it's something to do with BackendCombined? 

Also, the caldav section looks like it refers to a separate server - but one that looks like it contains the same php files as z-push? Is that a separate product or the z-push one? 

I'm confused how all this hangs together :-)

Jason

**Comment by dupondje** [comment]
The config.php has already set some default settings for BackendCombined.
Check the file, it should be quite clear on how to use :)
