### ISSUE TITLE
Where is iCalendar.php?

### ISSUE THREAD

**Issue by Scoutx66** [dupondje/PHP-Push-2#46]
I cannot find the file "iCalendar.php" which gets included by caldav.php

**Comment by dupondje** [comment]
Its in libawl-php
http://packages.debian.org/wheezy/all/libawl-php/filelist

Install it and enjoy :)

**Comment by ekacnet** [comment]
ok for libawl-php but then it needs the postgresql extensions for php ... seems a bit overkill ...

**Comment by dupondje** [comment]
Why would you need PostgresSQL extensions for PHP?

**Comment by ekacnet** [comment]
From a debian 6.0 the libawl-php package contain this line in the iCalendar.php:
require_once('PgQuery.php');

And the logs starts to show 

<title>PostgreSQL Support Not Present</title>

<h1>PostgreSQL Support Not Present</h1>

<h3>PHP is not configured to support the PostgreSQL database</h3>

<p>You need to ensure that the PostgreSQL support module is installed, and then to configure
it in your php.ini file by adding a line like this:</p>

<pre>
extension=pgsql.so
</pre>


Removing this require do the trick but that's not clean.

**Comment by dupondje** [comment]
We could include a modified copy of iCalendar.php without the PostgreSQL extension. But is it worth it?
99% of the users run the davical on the same server, which also needs PostgreSQL extension, so ...

**Comment by dupondje** [comment]
And the new version (that will come in wheezy), will have no more dependency on PostgreSQL.

**Comment by ekacnet** [comment]
Well I'm working currently to have calendar support on plain imap (using the kolab storage format) so I need iCalendar.php but I don't have a postgresql server as I don't have a ical server.
