### ISSUE TITLE
CardDAV support

### ISSUE THREAD

**Issue by fmbiete** [dupondje/PHP-Push-2#47]
Is there any CardDAV support??

I can get to work my calendar with the CalDAV backend and my DAVICAL server. But in the same DaviCal instance the user has another collection with contacts.

Is it possible? Or do I need to search for another backend and load it from the BackendCombined???

Thank you very much

**Comment by dupondje** [comment]
There is no carddav support included at this moment. As I do not use Carddav (for various reasons) I will not implement this.
But if you have time, and can code PHP, feel free to supply a carddav backend.
