### ISSUE TITLE
Caldav ASV 12 and 14 support

### ISSUE THREAD

**Issue by fmbiete** [dupondje/PHP-Push-2#54]
Hi,
I'm adding in my fork (developing branch) support for the EAS 12 and 14 tags. That fix some problems when using with the last version of IMAP/Combined/Caldav and Android.

Are you thought of pushing your backend into Z-Push??

**Comment by dupondje** [comment]
I will not push my caldav/ldap backend to Z-Push. As pushing those to Z-Push, means Zarafa becomes owner of the code, which is not something we want.
But ofcourse if we fix things in the other parts (like Imap backend etc) its highly recommended to push them to Z-Push :)
