### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by rrupi** [dupondje/PHP-Push-2#58]
Hi,
it seems there is a file missing:
caldav-client-v2.php -> require_once(XMLDocument.php)

/r

**Comment by dupondje** [comment]
Missing description?

**Comment by rrupi** [comment]
sry.. not used to the interface and presed enter too fast :)

**Comment by erwinwildenburg** [comment]
Go to your php.ini and change the include path value to:
include_path /usr/share/awl/inc
