### ISSUE TITLE
caldav.php:546 date_diff() expects parameter 2 to be DateTime, integer given (2)

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#7]
PHP-Push-2/backend/caldav.php:546 date_diff() expects parameter 2 to be DateTime, integer given (2)

The only update for caldav.php seems to be this line:

545c545
## < $begin = date_create("@" . $message->starttime);

> $begin = $start = date_create("@" . $message->starttime);

**Comment by dupondje** [comment]
Could you give me the data of the .ics file?

Thanks!

**Comment by fortiko** [comment]
I know the name from the log file (E222ED0A-5969-4359-A3BA-81AB36424F59.ics), but have no idea where to find it. It is not in /var/lib/z-push... any idea?

**Comment by dupondje** [comment]
davical url:

http://calendar/caldav.php/home/E222ED0A-5969-4359-A3BA-81AB36424F59.ics

**Comment by fortiko** [comment]
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//iCal 4.0.4//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Madrid
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:GMT+02:00
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:GMT+01:00
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20120306T143104Z
UID:E222ED0A-5969-4359-A3BA-81AB36424F59
DTEND;TZID=Europe/Madrid:20120329T170000
TRANSP:OPAQUE
SUMMARY:Renew q.ES archive certificate
DTSTART;TZID=Europe/Madrid:20120329T160000
DTSTAMP:20120329T121852Z
SEQUENCE:2
BEGIN:VALARM
X-WR-ALARMUID:54FDFF1A-1EB6-4626-9ECF-54C0F13EB892
TRIGGER;VALUE=DATE-TIME:20120330T121852Z
DESCRIPTION:Default Mozilla Description
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by fortiko** [comment]
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//iCal 4.0.4//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Madrid
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:GMT+02:00
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:GMT+01:00
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20120306T143104Z
UID:E222ED0A-5969-4359-A3BA-81AB36424F59
DTEND;TZID=Europe/Madrid:20120329T170000
TRANSP:OPAQUE
SUMMARY:Renew q.ES archive certificate
DTSTART;TZID=Europe/Madrid:20120329T160000
DTSTAMP:20120329T121852Z
SEQUENCE:2
BEGIN:VALARM
X-WR-ALARMUID:54FDFF1A-1EB6-4626-9ECF-54C0F13EB892
TRIGGER;VALUE=DATE-TIME:20120330T121852Z
DESCRIPTION:Default Mozilla Description
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by fortiko** [comment]
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//iCal 4.0.4//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Madrid
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:GMT+02:00
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:GMT+01:00
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20120306T143104Z
UID:E222ED0A-5969-4359-A3BA-81AB36424F59
DTEND;TZID=Europe/Madrid:20120329T170000
TRANSP:OPAQUE
SUMMARY:Renew q.ES archive certificate
DTSTART;TZID=Europe/Madrid:20120329T160000
DTSTAMP:20120329T121852Z
SEQUENCE:2
BEGIN:VALARM
X-WR-ALARMUID:54FDFF1A-1EB6-4626-9ECF-54C0F13EB892
TRIGGER;VALUE=DATE-TIME:20120330T121852Z
DESCRIPTION:Default Mozilla Description
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by dupondje** [comment]
Fixed in master now.
