### ISSUE TITLE
Baikal support

### ISSUE THREAD

**Issue by somecallmemike** [dupondje/PHP-Push-2#71]
Per the merge, I am reposting the request for Baikal support (https://github.com/jeromeschneider/Baikal).

**Comment by cisiqo** [comment]
the pro https://github.com/cisiqo/calsync2  support Baikal,maybe can help you

**Comment by dupondje** [comment]
Baikal is just a CalDAV server? So it should just work with the current code...

**Comment by somecallmemike** [comment]
Thanks for the feedback, I could not get Baikal working with php-push-2.  Most likely I am using a misconfigured cal/card dav configuration.  If it's not too much trouble could you add documentation for connecting to a Baikal installation to the Readme?

**Comment by flashtopia** [comment]
Baikal is nearly dead with few updates in the last months.
I think the project needs to be absorbed or taken over by someone else.
