### ISSUE TITLE
Add support for IMAP METADATA backend

### ISSUE THREAD

**Issue by somecallmemike** [dupondje/PHP-Push-2#73]
The folks at Kolab have developed an interesting model for storing cal, card, task, etc. information using the METADATA extension of IMAP, you can read about it here: https://wiki.kolab.org/Kolab_3.0_Storage_Format

This approach is compelling as it centralizes all the storage of data along with the user's messages, and allows authentication to happen against one system.  Considering you can also use the METADATA backend using the Kolab roundcube plugins there is already support for this backend in an open source webmail client.

A good source for code would be the roundcube plugins which interface with the IMAP METADATA extension located here: http://www.kolab.org/content/roundcubemail-plugins-kolab

**Comment by somecallmemike** [comment]
Looks like there are quite a few issues that are not acknowledged, is this project dead?

**Comment by dupondje** [comment]
This seems quite useless?
Kolab already has a ActiveSync server
http://www.kolab.org/about/syncroton
