### ISSUE TITLE
Calendar items appear and disappear on iOS

### ISSUE THREAD

**Issue by fortiko** [dupondje/PHP-Push-2#8]
Showing all calendars (with 1 AS calendar) works with colors.
Disabling all other cals still shows AS cal fine (with color).
After adding an event to AS calendar all events disappear. When re-enabling all calendars (including AS), everthing shows again.
And on top of it all, the event is NOT created in AS calendar!

**Comment by dupondje** [comment]
Like for all the bugs, give me a debug log for this.

**Comment by fortiko** [comment]
Solved, probably related to the other issue about not syncing all events correctly.
