### ISSUE TITLE
How about contributing to Z-Push?

### ISSUE THREAD

**Issue by fmbiete** [dupondje/PHP-Push-2#93]
Hi @dupondje 

Zarafa/Z-Push has opened again the contribution process. They have changed the requisites so you only need to commit your code under the AGPLv3 license.

I think thats a good change, so how about contributing your backends?? You can use the code available in my repo since it's adapted to the z-push 2.1 structure.

Regards,
Francisco Miguel Biete

**Comment by dupondje** [comment]
So that means the code isn't property of Zarafa anymore when you commit it?

**Comment by fmbiete** [comment]
Yes, the copyright of your code will remain yours, you are only licensing it as AGPL.

**Comment by dupondje** [comment]
Great! Feel free to commit it then :) You got my approval.

**Comment by fmbiete** [comment]
Wonderful!!
I have commited them (BackendLDAP and BackendCalDAV) and made a post in your name.
http://z-push.sourceforge.net/phpbb/viewtopic.php?f=5&t=2472
Maybe it would be nice to log into z-push forum and confirm it.

Regards,

**Comment by arved** [comment]
if there is still any code I provided in here (maybe the CardDav part) feel free to contribute this to z-push

**Comment by fmbiete** [comment]
Hi @arved 
Sorry, last year I developed a completely new BackendCardDAV, because the existing one was messy and I didn't want to spend time in something that I couldn't contrib. I have pushed the new one, that supports davical, sogo, owncloud and sabredav...

Regards,
